# deploy/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cortex'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cortex-api'
    static_configs:
      - targets: ['cortex-api:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'cortex-trainer'
    static_configs:
      - targets: ['cortex-trainer:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'cortex-global'
    static_configs:
      - targets: ['cortex-global:9090']
    metrics_path: '/metrics'
    scheme: 'http'